// ─── TECH STACK SECTION CONSTANTS ──────────────────────────────────────────
// T0.01: Local files: react.png, node.png, tailwind.png
// Missing logos use Devicons CDN (zero 404s, always available)

const DEVICON = (name, variant = 'original') =>
  `https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/${name}/${name}-${variant}.svg`

export const TECH_STACK_DATA = [
  {
    id: 'nextjs',
    name: 'Next.js',
    level: 'Advanced',
    description: 'React framework for production — hybrid static and server rendering, smart bundling, route prefetching, and zero config.',
    logoSrc: DEVICON('nextjs', 'original'),
    isFeatured: false,
    size: { desktop: 90, tablet: 74, mobile: 62 },
    glowColor: 'rgba(255,255,255,0.2)',
    glowIntensity: 'none',
    ringStyle: 'none',
    position: {
      desktop: { left: '42%', top: '12%' },
      tablet:  { left: '45%', top: '15%' },
      mobile:  { left: 'calc(52% - 31px)', top: '24%' },
    },
  },
  {
    id: 'threejs',
    name: 'Three.js',
    level: 'Advanced',
    description: 'Powerful WebGL library for creating 3D graphics in the browser. Enables immersive 3D experiences, physics, and shaders.',
    logoSrc: new URL('../assets/images/tech-stack/three-js.png', import.meta.url).href,
    isFeatured: false,
    size: { desktop: 95, tablet: 78, mobile: 65 },
    glowColor: '#ffffff',
    glowIntensity: 'medium',
    ringStyle: 'none',
    position: {
      desktop: { left: '22%', top: '18%' },
      tablet:  { left: '20%', top: '22%' },
      mobile:  { left: 'calc(22% - 32px)', top: '35%' },
    },
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    level: 'Expert',
    description: 'The backbone of the web. Deep mastery of core concepts, ES6+, and asynchronous programming patterns.',
    logoSrc: new URL('../assets/images/tech-stack/js.png', import.meta.url).href,
    isFeatured: false,
    size: { desktop: 95, tablet: 78, mobile: 65 },
    glowColor: '#F7DF1E',
    glowIntensity: 'medium',
    ringStyle: 'none',
    position: {
      desktop: { left: '62%', top: '18%' },
      tablet:  { left: '70%', top: '20%' },
      mobile:  { left: 'calc(88% - 32px)', top: '56%' },
    },
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    level: 'Intermediate',
    description: 'Document-oriented NoSQL database — flexible schema design, horizontal scaling, and native JSON storage.',
    logoSrc: DEVICON('mongodb', 'original'),
    isFeatured: false,
    size: { desktop: 85, tablet: 70, mobile: 58 },
    glowColor: '#00ED64',
    glowIntensity: 'low',
    ringStyle: 'none',
    position: {
      desktop: { left: '85%', top: '12%' },
      tablet:  { right: '10%', top: '15%' },
      mobile:  { left: 'calc(80% - 29px)', top: '42%' },
    },
  },
  {
    id: 'react',
    name: 'React',
    level: 'Expert',
    description: 'Component-based UI library for building fast, interactive interfaces with a declarative programming model and powerful ecosystem.',
    logoSrc: new URL('../assets/images/tech-stack/react.png', import.meta.url).href,
    isFeatured: true,
    size: { desktop: 154, tablet: 124, mobile: 110 },
    glowColor: '#61DAFB',
    glowIntensity: 'high',
    ringStyle: 'sonar',
    position: {
      desktop: { left: '14%', top: 'calc(48% - 77px)' },
      tablet:  { left: '15%', top: 'calc(48% - 62px)' },
      mobile:  { left: 'calc(50% - 55px)', top: 'calc(55% - 55px)' },
    },
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    level: 'Advanced',
    description: 'JavaScript runtime built on V8 for scalable server-side and network applications with non-blocking I/O.',
    logoSrc: new URL('../assets/images/tech-stack/node.png', import.meta.url).href,
    isFeatured: false,
    size: { desktop: 106, tablet: 84, mobile: 72 },
    glowColor: '#68A063',
    glowIntensity: 'medium',
    ringStyle: 'glow-ring',
    position: {
      desktop: { left: '76%', top: '44%' },
      tablet:  { right: '15%', top: '48%' },
      mobile:  { left: 'calc(38% - 36px)', top: '82%' },
    },
  },
  {
    id: 'tailwind',
    name: 'Tailwind CSS',
    level: 'Expert',
    description: 'Utility-first CSS framework for rapid UI development — atomic classes, design tokens, and zero runtime overhead.',
    logoSrc: new URL('../assets/images/tech-stack/tailwind.png', import.meta.url).href,
    isFeatured: false,
    size: { desktop: 85, tablet: 70, mobile: 58 },
    glowColor: '#38BDF8',
    glowIntensity: 'low',
    ringStyle: 'none',
    position: {
      desktop: { left: '8%', bottom: '15%' },
      tablet:  { left: '8%', bottom: '18%' },
      mobile:  { left: 'calc(20% - 29px)', top: '68%' },
    },
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    level: 'Advanced',
    description: 'Strongly typed superset of JavaScript that compiles to plain JS — adds static typing, interfaces, and advanced IDE tooling.',
    logoSrc: DEVICON('typescript', 'original'),
    isFeatured: false,
    size: { desktop: 105, tablet: 85, mobile: 74 },
    glowColor: '#3178C6',
    glowIntensity: 'medium',
    ringStyle: 'none',
    isSquare: true,
    position: {
      desktop: { left: '46%', bottom: '15%' },
      tablet:  { left: '48%', bottom: '18%' },
      mobile:  { left: 'calc(58% - 37px)', top: '72%' },
    },
  },
  {
    id: 'redux',
    name: 'Redux Toolkit',
    level: 'Advanced',
    description: 'The official, opinionated, batteries-included toolset for efficient Redux development. Simplifies store setup, reducers, and immutable state updates.',
    logoSrc: new URL('../assets/images/tech-stack/redux.png', import.meta.url).href,
    isFeatured: false,
    size: { desktop: 105, tablet: 85, mobile: 72 },
    glowColor: '#764ABC',
    glowIntensity: 'medium',
    ringStyle: 'glow-ring',
    position: {
      desktop: { left: '84%', bottom: '15%' },
      tablet:  { right: '8%', bottom: '18%' },
      mobile:  { left: 'calc(78% - 36px)', top: '82%' },
    },
  },
]

export const TECH_STACK_PARTICLE_COUNT_DESKTOP = 80
export const TECH_STACK_PARTICLE_COUNT_MOBILE  = 40
export const TECH_FEATURED_ID = 'react'
